// Generated by data class generator
// DO NOT MODIFY BY HAND

part of 'async_state.dart';

mixin _AsyncResult<T> {
  abstract final String message;
  abstract final String code;
  abstract final T? data;
  abstract final bool isRefresh;
  abstract final AsyncStatus status;
  abstract final Map<String, dynamic> extras;

  _AsyncResultCopyWith<T> get copyWith => _AsyncResultCopyWith<T>._(this);

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    if (other is! AsyncResult) return false;

    if (message != other.message) {
      return false;
    }
    if (code != other.code) {
      return false;
    }
    if (data != other.data) {
      return false;
    }
    if (isRefresh != other.isRefresh) {
      return false;
    }
    if (status != other.status) {
      return false;
    }
    if (!DeepCollectionEquality().equals(extras, other.extras)) {
      return false;
    }
    return true;
  }

  @override
  int get hashCode {
    return Object.hashAll([
      message,
      code,
      data,
      isRefresh,
      status,
      DeepCollectionEquality().hash(extras),
    ]);
  }

  @override
  String toString() {
    return 'AsyncResult(message: $message, code: $code, data: $data, isRefresh: $isRefresh, status: $status, extras: $extras)';
  }
}

/// Helper class for chained copyWith operations
class _AsyncResultCopyWith<T> {
  final _AsyncResult<T> _instance;
  const _AsyncResultCopyWith._(this._instance);

  /// Update message field
  AsyncResult<T> message(String? value) {
    return AsyncResult<T>(
      message: value ?? _instance.message,
      code: _instance.code,
      data: _instance.data,
      isRefresh: _instance.isRefresh,
      status: _instance.status,
      extras: _instance.extras,
    );
  }

  /// Update code field
  AsyncResult<T> code(String? value) {
    return AsyncResult<T>(
      message: _instance.message,
      code: value ?? _instance.code,
      data: _instance.data,
      isRefresh: _instance.isRefresh,
      status: _instance.status,
      extras: _instance.extras,
    );
  }

  /// Update data field
  AsyncResult<T> data(T? value) {
    return AsyncResult<T>(
      message: _instance.message,
      code: _instance.code,
      data: value,
      isRefresh: _instance.isRefresh,
      status: _instance.status,
      extras: _instance.extras,
    );
  }

  /// Update isRefresh field
  AsyncResult<T> isRefresh(bool? value) {
    return AsyncResult<T>(
      message: _instance.message,
      code: _instance.code,
      data: _instance.data,
      isRefresh: value ?? _instance.isRefresh,
      status: _instance.status,
      extras: _instance.extras,
    );
  }

  /// Update status field
  AsyncResult<T> status(AsyncStatus? value) {
    return AsyncResult<T>(
      message: _instance.message,
      code: _instance.code,
      data: _instance.data,
      isRefresh: _instance.isRefresh,
      status: value ?? _instance.status,
      extras: _instance.extras,
    );
  }

  /// Update extras field
  AsyncResult<T> extras(Map<String, dynamic>? value) {
    return AsyncResult<T>(
      message: _instance.message,
      code: _instance.code,
      data: _instance.data,
      isRefresh: _instance.isRefresh,
      status: _instance.status,
      extras: value ?? _instance.extras,
    );
  }

  /// Traditional copyWith method
  AsyncResult<T> call({
    String? message,
    String? code,
    T? data,
    bool? isRefresh,
    AsyncStatus? status,
    Map<String, dynamic>? extras,
  }) {
    return AsyncResult<T>(
      message: message ?? _instance.message,
      code: code ?? _instance.code,
      data: data ?? _instance.data,
      isRefresh: isRefresh ?? _instance.isRefresh,
      status: status ?? _instance.status,
      extras: extras ?? _instance.extras,
    );
  }
}
